name: ZAP-Hosting ESX Pack
version: v1.5
author: ZAP-Hosting.com & the ESX Team
description: An ESX pack with additional bug-fixes, based on esx-legacy.

variables:
  steam_webApiKey: "none"

tasks:
  # Download default CFX resources
  - action: download_github
    src: https://github.com/citizenfx/cfx-server-data
    ref: 44fc68d7ee1b94ad67a211a6ff8234ce4ff760c8
    subpath: resources
    dest: ./resources

  - action: ensure_dir
    path: ./tmp/

  - action: download_github
    src: https://github.com/zaphosting/esx_12_recipe 
    dest: ./tmp/zap_esx
    
  - action: download_github
    src: https://github.com/zaphosting/esx_12
    dest: ./resources/[esx]
    ref: 3317fe4e4a9006226904f519f6270e5b823ace30

  - action: move_path
    src: ./tmp/zap_esx/server.cfg
    dest: ./server.cfg

  - action: move_path
    src: ./tmp/zap_esx/zap96x96.png
    dest: ./zap96x96.png

  - action: replace_string
    file: /resources/[esx]/esx_final.sql
    search: "es_extended"
    replace: "{{dbName}}"

  - action: connect_database
  - action: query_database
    file: ./resources/[esx]/esx_final.sql

  # other required resources
  - action: download_github
    src: https://github.com/Blumlaut/EasyAdmin
    ref: fd7f3054dfc0708cb50e9d5720a1ca616095dbd7
    dest: ./resources/EasyAdmin

  - action: download_github
    src: https://github.com/Bob74/bob74_ipl
    ref: master
    dest: ./resources/bob74_ipl
    
  - action: remove_path
    path: ./tmp
